nada = None 
cadena = "hola soy martin el programador web"
entero = 99
flotante = 4.2
booleano = False 
lista = [10, 20, 30, 100]
listaString =[10, "treinta", 40, "pez"]
tuplaNoCambia = ("master", "en", "python")
diccionario = {
"nombre" : "martin maldonado",
"apellido" : "maldonado",
"curso" : "master en python"}
rango = range(9)
print(type(rango))

testo = "hola soy un texto"
numerito = str(776)
print(type(numerito))

print(testo + " "+ numerito)

numerito = float(776)
print(numerito)
numerito = int(776)
# print(numerito)



